name: cmangos-server
base: core22
version: '1.0'
summary: "Custom World of Warcraft server using CMaNGOS"
description: |
  A custom World of Warcraft server built with CMaNGOS, including modifications
  for the hardest level process you will ever witness and revamped skill trees.

grade: stable
confinement: strict

apps:
  mangosd:
    command: $SNAPCRAFT_PART_INSTALL/bin/mangosd -c $SNAPCRAFT_PART_INSTALL/etc/mangosd.conf
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind]
    environment:
      MYSQL_ROOT_PASSWORD: $SNAP_COMMON/mangos
      MYSQL_UNIX_PORT: $SNAP_COMMON/mysql.sock

  realmd:
    command: $SNAPCRAFT_PART_INSTALL/bin/realmd -c $SNAPCRAFT_PART_INSTALL/etc/realmd.conf
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind]
    environment:
      MYSQL_ROOT_PASSWORD: $SNAP_COMMON/mangos123
      MYSQL_UNIX_PORT: $SNAP_COMMON/mysql.sock

parts:
  cmangos-server:
    plugin: cmake
    source: releases/cmangos-server-build.zip
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-packages:
      - build-essential
      - gcc-12
      - g++-12
      - automake
      - git-core
      - autoconf
      - make
      - patch
      - libmysql++-dev
      - mysql-server
      - libtool
      - libssl-dev
      - grep
      - binutils
      - zlib1g-dev
      - libbz2-dev
      - libboost-all-dev
      - curl
      - libcurl4-openssl-dev
    stage-packages:
      - mysql-server
      - mysql-client
      - libmysqlclient21
      - libcurl4
      - libldap-2.5-0
      - libsasl2-2
      - libnghttp2-14
      - libpsl5
      - librtmp1
    build-snaps:
      - cmake/latest/stable
    build-environment:
      - GIT_SSL_NO_VERIFY: 1
      - PATH: /snap/bin:$PATH
    override-build: |
      update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 120 \
          --slave /usr/bin/g++ g++ /usr/bin/g++-12
      export CC=gcc
      export CXX=g++
      cmake ../src -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=$SNAPCRAFT_PART_INSTALL -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DBUILD_MODULES=ON -DBUILD_MODULE_MANGOSTOOL=ON
      make -j6
      make install
      cp $SNAPCRAFT_PART_INSTALL/etc/mangosd.conf.dist $SNAPCRAFT_PART_INSTALL/etc/mangosd.conf
      cp $SNAPCRAFT_PART_INSTALL/etc/realmd.conf.dist $SNAPCRAFT_PART_INSTALL/etc/realmd.conf
