name: cmangos-server
base: core22
version: '1.0'
summary: "Custom World of Warcraft server using CMaNGOS"
description: |
  A custom World of Warcraft server built with CMaNGOS, including modifications
  for the hardest level process you will ever witness and revamped skill trees.

grade: stable
confinement: strict

apps:
  mangosd:
    command: parts/cmangos-server/build/bin/mangosd
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind]
    environment:
      MYSQL_ROOT_PASSWORD: $SNAP_COMMON/mangos
      MYSQL_UNIX_PORT: $SNAP_COMMON/mysql.sock

  realmd:
    command: parts/cmangos-server/build/bin/realmd
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind]
    environment:
      MYSQL_ROOT_PASSWORD: $SNAP_COMMON/mangos123
      MYSQL_UNIX_PORT: $SNAP_COMMON/mysql.sock

parts:
  cmangos-server:
    plugin: cmake
    source: releases/0.1/Test-Build.zip
    build-environment:
    - CFLAGS: "-DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DBUILD_MODULES=ON -DBUILD_MODULE_MANGOSTOOL=ON"
    build-packages:
      - build-essential
      - gcc-12
      - g++-12
      - automake
      - git-core
      - autoconf
      - make
      - patch
      - libmysql++-dev
      - mysql-server
      - libtool
      - libssl-dev
      - grep
      - binutils
      - zlib1g-dev
      - libbz2-dev
      - cmake
      - libboost-all-dev
    stage-packages:
      - mysql-server
      - mysql-client
    override-build: |
      update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 120 \
          --slave /usr/bin/g++ g++ /usr/bin/g++-12
      export CC=gcc
      export CXX=g++
      cmake $SNAPCRAFT_PART_SRC -DCMAKE_INSTALL_PREFIX=/usr/local
      make -j$(nproc)
      make install